yml version: '3'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: korea2tv

    ports:
      - "3306:3306"
    networks:
      - korea2tv-network
    restart: unless-stopped

  spring-app:
    build:
      context: ./Korea2Tv-Backend
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/korea2tv
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "" # Empty password
    networks:
      - korea2tv-network
    restart: unless-stopped

  angular-app:
    build:
      context: ./Korea2Tv-Frontend
      dockerfile: DockerFile
    ports:
      - "4200:4200"
    depends_on:
      - spring-app
    networks:
      - korea2tv-network
    restart: unless-stopped

networks:
  korea2tv-network:
    driver: bridge